language: node_js
node_js:
  - "10"
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - yarn install

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: chingu-jobbatical-clone
